###
DELETE http://localhost:9999/connections/fa85977e-c042-4a77-9a74-8664c2cc3e7f
Content-Type: application/json

###
POST http://localhost:9999/connections
Content-Type: application/json

{
  "name": "Dock Ready",
  "email": "ready.to.dock@maybe.com",
  "shipping_address": "The docks",
  "billing_address": ""
}

###
GET http://localhost:9999/connections
Content-Type: application/json

###
GET http://localhost:9999/connections/feea2bc0-db76-470d-9175-9bd35900b762
Content-Type: application/json

###
PUT http://localhost:9999/connections/feea2bc0-db76-470d-9175-9bd35900b762
Content-Type: application/json

{
  "name": "Example Person",
  "email": "example.person@yes.com",
  "shipping_address": "The docks",
  "billing_address": "Free trial Street 313"
}

###
GET http://localhost:9999/log
Content-Type: application/json